# Generated by Django 2.2.7 on 2019-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaar',
            options={'verbose_name_plural': 'Jaren'},
        ),
    ]
