# Generated by Django 2.2.7 on 2019-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191120_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jaar',
            name='id',
        ),
        migrations.AlterField(
            model_name='jaar',
            name='aantal_punten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jaar',
            name='jaar_naam',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
